### ISSUE TITLE
Plugin doesn't load on Mac (Apple Silicon)

### ISSUE THREAD

**Issue by hibnotix** [royshil/obs-localvocal#3] opened 2023-08-16 18:55 UTC
Here is the log file after supposedly installing the Plugin with the .pkg
[2023-08-16 19-53-04.txt](https://github.com/royshil/obs-localvocal/files/12362620/2023-08-16.19-53-04.txt)

**Comment by royshil** [comment] 2023-08-17 04:58
Very strange
It says it can't find the OBS frontend Library

Is your OBS install standard? Or Portable?

**Comment by royshil** [comment] 2023-08-17 04:59
Oh you're running OBS v28
The plugin needs v29
Please upgrade and try again

Thanks for the feedback!

**Comment by royshil** [comment] 2023-08-23 08:46
i'm closing since i think the obs version is the cause of failure

**Closed by royshil** 2023-08-23 08:46 UTC
