### ISSUE TITLE
Crash upon adding audio filter

### ISSUE THREAD

**Issue by Landiie** [royshil/obs-localvocal#2] opened 2023-08-14 21:27 UTC
Hi! Plugin looks like a great concept, however, I add it as an audio filter to my microphone and after a bit of waiting it crashes with no errors or anything. I can provide any obs logs if needed!

**Comment by royshil** [comment] 2023-08-14 22:11
Please send logs! I'm glad to take a look and find a fix for the crash
You can grab both the OBS running log as well as the crash log, both are saved in the OBS directory

**Comment by Seamas73** [comment] 2023-08-15 12:30
I confirm this bug
[Crash 2023-08-15 15-16-51.txt](https://github.com/royshil/obs-localvocal/files/12344026/Crash.2023-08-15.15-16-51.txt)
[Crash 2023-08-15 15-15-39.txt](https://github.com/royshil/obs-localvocal/files/12344028/Crash.2023-08-15.15-15-39.txt)
[2023-08-15 15-16-02.txt](https://github.com/royshil/obs-localvocal/files/12344032/2023-08-15.15-16-02.txt)
[2023-08-15 15-12-58.txt](https://github.com/royshil/obs-localvocal/files/12344033/2023-08-15.15-12-58.txt)

**Comment by royshil** [comment] 2023-08-15 20:23
the logs definitely point to a crash in the plugin code - but can't find out where exactly

can you try to add the filter to a new audio source in a new scene?
can also be not a microphone rather an audio file playback

**Comment by Sakare14** [comment] 2023-08-16 10:57
I tried on a mvk file it worked, but on mic in crash.

**Comment by LaughterOnWater** [comment] 2023-08-18 12:56
[Crash 2023-08-18 08-45-52.txt](https://github.com/royshil/obs-localvocal/files/12379410/Crash.2023-08-18.08-45-52.txt)

**Comment by royshil** [comment] 2023-08-19 01:31
Ok this log is revealing. The crash in on the create function.
I can add more safeguards to make sure it doesn't crash and properly report the errors.
It also seems like this is afflicting AMD Ryzen machines more than others.

**Comment by royshil** [comment] 2023-08-19 22:39
@LaughterOnWater @Seamas73 @Landiie @skubia can y'all please test the attempted fix on https://github.com/royshil/obs-localvocal/actions/runs/5913832735?pr=4#artifacts ?
i believe i know what the problem was and installed a fix for it.
Thanks! 🙏

**Comment by Landiie** [comment] 2023-08-20 00:56
sadly, still getting a crash with the attempted fix version D: here is my crash log!

[Crash 2023-08-19 17-54-19.txt](https://github.com/royshil/obs-localvocal/files/12386957/Crash.2023-08-19.17-54-19.txt)

**Comment by royshil** [comment] 2023-08-20 04:26
@Landiie let's try the latest build https://github.com/royshil/obs-localvocal/actions/runs/5915325860?pr=4#artifacts
can you plz also include the OBS logs in addition to the crash logs? 🙏

**Comment by Destroy666x** [comment] 2023-08-20 20:54
I also had a crash with 0.0.1 with Intel CPU and the last comment's build has no issue anymore.

**Comment by kitlivingstone** [comment] 2023-08-21 12:45
lol, you beat me to asking.  I just ran the updates and issue still occurs.  log for that above.

**Comment by royshil** [comment] 2023-08-21 12:50
@kitlivingstone the log above suggests a problem in the creation fucntion - can you also post the crash log? the OBS folder has a folder for crash logs, e.g. in Windows it's `%appdata%/obs-studio/crashes` or something to that effect

**Comment by kitlivingstone** [comment] 2023-08-21 12:51
Sure, here you go

[Crash 2023-08-21 08-43-28.txt](https://github.com/royshil/obs-localvocal/files/12396098/Crash.2023-08-21.08-43-28.txt)

**Comment by royshil** [comment] 2023-08-22 05:41
@kitlivingstone can you please try https://github.com/royshil/obs-localvocal/actions/runs/5930845619#artifacts ? i've added log lines to pin down where the exception is happening

for me the bug was resolved, so we should find the bug on your OS

**Comment by Landiie** [comment] 2023-08-22 06:31
hey, just tried the build above and i crashed again on windows, no crash log this time. Here is the actual regular log this time!

[2023-08-21 23-27-06.txt](https://github.com/royshil/obs-localvocal/files/12405552/2023-08-21.23-27-06.txt)

**Comment by royshil** [comment] 2023-08-22 07:04
@Landiie can you please try https://github.com/royshil/obs-localvocal/actions/runs/5935465038#artifacts ? i'm trying a different way in initializing pointers

**Comment by royshil** [comment] 2023-08-22 14:02
@kitlivingstone thank you so much!
can you also include the regular log? since i'm now sending more log lines there to try to find the offending code

**Comment by kitlivingstone** [comment] 2023-08-22 14:21
@royshil  sure.  Here you are.
[2023-08-22 10-02-57.txt](https://github.com/royshil/obs-localvocal/files/12409670/2023-08-22.10-02-57.txt)

**Comment by royshil** [comment] 2023-08-22 16:11
i'm able to reproduce this problem now on my Windows setup. so i'm chasing down the bug at the moment. i'll have an update later..

**Comment by kitlivingstone** [comment] 2023-08-22 16:16
Sounds good @royshil.  Looking forward to getting this working here.  Honestly, I like the roadmap you have set for future features too.  Happy to beta test if needed in the future.

**Comment by royshil** [comment] 2023-08-25 09:31
can y'all try the latest build https://github.com/royshil/obs-localvocal/actions/runs/5974152158#artifacts plz?

**Comment by kitlivingstone** [comment] 2023-08-25 14:12
> can y'all try the latest build https://github.com/royshil/obs-localvocal/actions/runs/5974152158#artifacts plz?

@royshil  - Whatever you did seems to do the trick - https://youtu.be/KbzCHdikwKs

**Comment by royshil** [comment] 2023-09-04 23:09
@kitlivingstone and @nacalai 
are you getting any action from the laest build form the PR or does it always crash w/o log for you as soon as you add the filter?

**Comment by stiblook** [comment] 2023-09-05 12:52
experiencing the same error on linux as well... so excited to try this new plugin!

**Comment by kitlivingstone** [comment] 2023-09-05 14:16
@royshil, if it is the same one at https://github.com/royshil/obs-localvocal/actions/runs/5974152158#artifacts, I downloaded it just now and tried and it is still crashing on adding filter.  (sorry it took me a bit to respond. Prepping for festivals and family in town).

**Comment by stiblook** [comment] 2023-09-05 18:23
Initially the build artifact from the action worked  great, but as soon as I set the output and the model, it just hanged, after sometime it unfroze and worked, but on again starting obs, it crashes, that too randomly, if I start obs again and again, it just sometimes works!

**Comment by royshil** [comment] 2023-09-07 02:41
@kitlivingstone @stiblook @nacalai @Landiie @LaughterOnWater 
i think i'm on to something. can you please check https://github.com/royshil/obs-localvocal/actions/runs/6104677254?pr=4#artifacts ? 🙏 
for me it doesn't crash anymore on Windows, even if adding and removing many times and trying to get it to crash.

**Comment by stiblook** [comment] 2023-09-07 09:25
Works for me now! Thanks!

**Comment by royshil** [comment] 2023-09-08 14:14
OK i'm going to merge it in and close this issue
if anyone still is having problems please open a new issue

**Closed by royshil** 2023-09-08 14:14 UTC
Labels: bug
